import { index, integer, pgTable, primaryKey, text, timestamp, uuid } from 'drizzle-orm/pg-core'

export const users = pgTable('users', {
  id: uuid('id').primaryKey(),
  googleSub: text('google_sub').notNull().unique(),
  email: text('email').notNull(),
  name: text('name').notNull(),
  avatarUrl: text('avatar_url'),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull(),
})

/**
 * The group's shared roster. A person is not scoped to any match: the same
 * "Pollo" resolves to the same row whether he plays this weekend or next.
 */
export const people = pgTable('people', {
  id: uuid('id').primaryKey(),
  name: text('name').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull(),
})

export const matches = pgTable('matches', {
  id: uuid('id').primaryKey(),
  name: text('name').notNull().default(''),
  date: text('date').notNull(),
  videoProvider: text('video_provider'),
  videoId: text('video_id'),
  inviteCode: text('invite_code').notNull().unique(),
  createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull(),
})

export const matchMemberRoles = ['owner', 'tagger', 'viewer'] as const

export const matchMembers = pgTable(
  'match_members',
  {
    matchId: uuid('match_id')
      .notNull()
      .references(() => matches.id, { onDelete: 'cascade' }),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    role: text('role', { enum: matchMemberRoles }).notNull(),
    joinedAt: timestamp('joined_at', { withTimezone: true, mode: 'date' }).notNull(),
  },
  (table) => [
    primaryKey({ columns: [table.matchId, table.userId] }),
    index('match_members_user_id_idx').on(table.userId),
  ],
)

export const teams = pgTable(
  'teams',
  {
    id: uuid('id').primaryKey(),
    matchId: uuid('match_id')
      .notNull()
      .references(() => matches.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    color: text('color').notNull(),
    position: integer('position').notNull(),
  },
  (table) => [index('teams_match_id_idx').on(table.matchId)],
)

export const players = pgTable(
  'players',
  {
    id: uuid('id').primaryKey(),
    teamId: uuid('team_id')
      .notNull()
      .references(() => teams.id, { onDelete: 'cascade' }),
    personId: uuid('person_id')
      .notNull()
      .references(() => people.id, { onDelete: 'restrict' }),
    name: text('name').notNull(),
    position: integer('position').notNull(),
  },
  (table) => [index('players_team_id_idx').on(table.teamId)],
)

/**
 * `id` is generated by the client, not the database: it is what makes a
 * resent request idempotent (`ON CONFLICT (id) DO NOTHING`), which matters
 * once several people are tagging the same match concurrently.
 */
export const events = pgTable(
  'events',
  {
    id: uuid('id').primaryKey(),
    matchId: uuid('match_id')
      .notNull()
      .references(() => matches.id, { onDelete: 'cascade' }),
    playerId: uuid('player_id')
      .notNull()
      .references(() => players.id, { onDelete: 'cascade' }),
    teamId: uuid('team_id')
      .notNull()
      .references(() => teams.id, { onDelete: 'cascade' }),
    statId: text('stat_id').notNull(),
    delta: integer('delta').notNull(),
    videoMs: integer('video_ms'),
    createdBy: uuid('created_by').references(() => users.id, { onDelete: 'set null' }),
    createdAt: timestamp('created_at', { withTimezone: true, mode: 'date' }).notNull(),
    deletedAt: timestamp('deleted_at', { withTimezone: true, mode: 'date' }),
    deletedBy: uuid('deleted_by').references(() => users.id, { onDelete: 'set null' }),
    /**
     * Set when this event landed close enough in the video to another one of
     * the same player and statistic to plausibly be the same play — never
     * blocks the write, just flags it for a human to resolve. No foreign key:
     * a self-reference into the same table Postgres can insert in one
     * statement without deferring constraints, and the app never needs to
     * join through it.
     */
    possibleDuplicateOf: uuid('possible_duplicate_of'),
  },
  (table) => [
    index('events_match_id_video_ms_idx').on(table.matchId, table.videoMs),
    index('events_match_id_player_id_stat_id_idx').on(table.matchId, table.playerId, table.statId),
  ],
)

export const segmentStatuses = ['pending', 'in_progress', 'done'] as const

/**
 * A slice of the video one person is responsible for tagging. Purely a
 * coordination aid: it organises who covers what, it does not own the events
 * inside it — an event belongs to whichever segment its `videoMs` currently
 * falls in, not to a segment id, so redividing segments never touches
 * already-recorded data.
 */
export const segments = pgTable(
  'segments',
  {
    id: uuid('id').primaryKey(),
    matchId: uuid('match_id')
      .notNull()
      .references(() => matches.id, { onDelete: 'cascade' }),
    label: text('label').notNull(),
    startMs: integer('start_ms').notNull(),
    endMs: integer('end_ms').notNull(),
    assigneeUserId: uuid('assignee_user_id').references(() => users.id, { onDelete: 'set null' }),
    status: text('status', { enum: segmentStatuses }).notNull().default('pending'),
    position: integer('position').notNull(),
  },
  (table) => [index('segments_match_id_idx').on(table.matchId)],
)
